languageCode = "ja"
languageName = "Japanese"
weight = 2

title = "sforzando LLC. and Inc."
copyright = "&copy; 2022 sforzando LLC. and Inc."

[params]
  isoCode = "ja"
  displayName = "JPN"
  rtl = false

  dateFormat = "2006年1月2日"

  # mainSections = ["section1", "section2"]
  description = "sforzando LLC. and Inc. specializes in rapid and flexible prototyping with a focus on software development."

[author]
  name = "sforzando LLC. and Inc."
  image = "image/logo/1080x1080_ffffff.png"
  headline = "An international company specializing in prototyping."
  bio = "The headquarter was established in Japan in 2017. The following year, sforzando Inc. was established as a subsidiary in BC, Canada."
  links = [
      { email = "mailto:contact@sfz.dev" },
    #   { link = "/team" },
    #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #   { apple = "https://www.apple.com" },
    #   { blogger = "https://username.blogspot.com/" },
    #   { codepen = "https://codepen.io/username" },
    #   { dev = "https://dev.to/username" },
    #   { discord = "https://discord.gg/invitecode" },
    #   { dribbble = "https://dribbble.com/username" },
    #   { facebook = "https://facebook.com/username" },
    #   { flickr = "https://www.flickr.com/photos/username/" },
    #   { foursquare = "https://foursquare.com/username" },
      { github = "https://github.com/sforzando" },
    #   { gitlab = "https://gitlab.com/username" },
    #   { google = "https://www.google.com/" },
    #   { hashnode = "https://username.hashnode.dev" },
      { instagram = "https://instagram.com/sfzllc" },
    #   { keybase = "https://keybase.io/shin_sforzando" },
    #   { kickstarter = "https://www.kickstarter.com/profile/username" },
    #   { lastfm = "https://lastfm.com/user/username" },
    #   { linkedin = "https://linkedin.com/in/username" },
    #   { mastodon = "https://mastodon.instance/@username" },
    #   { medium = "https://medium.com/username" },
    #   { microsoft = "https://www.microsoft.com/" },
    #   { orcid = "https://orcid.org/userid" },
    #   { patreon = "https://www.patreon.com/username" },
    #   { pinterest = "https://pinterest.com/username" },
    #   { reddit = "https://reddit.com/user/username" },
    #   { researchgate = "https://www.researchgate.net/profile/username" },
    #   { slack = "https://workspace.url/team/userid" },
    #   { snapchat = "https://snapchat.com/add/username" },
    #   { soundcloud = "https://soundcloud.com/username" },
    #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #   { steam = "https://steamcommunity.com/profiles/userid" },
    #   { telegram = "https://t.me/username" },
    #   { tiktok = "https://tiktok.com/@username" },
    #   { tumblr = "https://username.tumblr.com" },
    #   { twitch = "https://twitch.tv/username" },
      { twitter = "https://twitter.com/sforzando_llc" },
    #   { whatsapp = "https://wa.me/phone-number" },
    #   { youtube = "https://youtube.com/username" },
  ]
