locale = "ja"
label = "日本語"
displayName = ":jp: To Jpn"
isoCode = "ja"
weight = 2
direction = "ltr"

title = "sforzando LLC. and Inc."
description = "sforzando LLC. and Inc. specializes in rapid and flexible prototyping with a focus on software development."
copyright = "&copy; 2022 sforzando LLC. and Inc."

dateFormat = "2006年01月02日"

[params.author]
name = "sforzando LLC. and Inc."
image = "img/logo/1080x1080_ffffff.png"
headline = "An international company specializing in prototyping."
bio = "Founded in Japan in 2017, with a subsidiary incorporated in British Columbia, Canada in 2018."
links = [
    { email = "mailto:contact@sfz.dev" },
  #   { link = "/teams" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
    { google = "https://maps.app.goo.gl/riCcb4iG1ZyUPkpU8" },
    { facebook = "https://facebook.com/sfzllc" },
    { instagram = "https://instagram.com/sfzllc" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/sforzando" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { keybase = "https://keybase.io/shin_sforzando" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { kofi = "https://ko-fi.com/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  #   { xing = "https://xing.com/profile/username" },
]
