# Lefthook configuration
# https://github.com/evilmartians/lefthook

pre-commit:
  commands:
    format:
      glob: "*.{js,ts,json,css,html}"
      run: npm run format
      stage_fixed: true

    test:
      run: task test
