[build]
  command = "hugo --theme=congo --gc --minify --baseURL $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "development"
  GO_VERSION = "1.19.4"
  TZ = "Asia/Tokyo"

[context.production.environment]
  HUGO_VERSION = "0.108.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.108.0"

[[redirects]]
  from = "https://sforzando.co.jp"
  to = "https://sfz.dev"
  status = 301
  force = true

[[redirects]]
  from = "https://sforzando.net"
  to = "https://sfz.dev"
  status = 301
  force = true

[[redirects]]
  from = "https://szk-engineering.com"
  to = "https://sfz.dev"
  status = 301
  force = true
