[build]
  command = "hugo --theme=congo --gc --minify --baseURL $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.18"
  TZ = "Asia/Tokyo"

[context.production.environment]
  HUGO_VERSION = "0.100.2"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.100.2"
