version: '3'

vars:
  TIMESTAMP:
    sh: date +%Y%m%d%H%M%S
  OS_NAME:
    sh: uname -s
  OPEN_TARGET: http://0.0.0.0:1313/

tasks:
  default:
    desc: 常用 - 開発サーバー起動
    cmds:
      - task: start

  setup:
    desc: 初期セットアップ
    cmds:
      - |
        if [ "{{.OS_NAME}}" = "Darwin" ]; then
          brew install direnv
          brew install git-cliff
          brew install git-secret
          brew install hugo
          brew install netlify-cli
          brew install --cask ngrok
        fi
      - git submodule update --init --recursive
      - task: reveal
      - direnv allow
      - |
        if [ "{{.OS_NAME}}" = "Darwin" ]; then
          say "The setup process is complete."
        fi

  install:
    desc: 依存パッケージをインストール
    cmds:
      - npm install
      - npm install --prefix themes/congo
      - npx playwright install --with-deps

  open:
    desc: 閲覧 - ブラウザで開く
    cmds:
      - |
        if [ "{{.OS_NAME}}" = "Darwin" ]; then
          open {{.OPEN_TARGET}}
        fi

  hide:
    desc: 秘匿 - git-secretで秘密情報を暗号化
    cmds:
      - git secret hide -vm

  reveal:
    desc: 暴露 - git-secretで秘密情報を復号化
    cmds:
      - git secret reveal -vf

  build-css:
    desc: 構築 - TailwindCSSをビルド
    cmds:
      - NODE_ENV=production ./themes/congo/node_modules/.bin/tailwindcss -c ./themes/congo/tailwind.config.js -i ./themes/congo/assets/css/main.css -o ./assets/css/compiled/main.css --jit

  start:
    desc: 開始 - Hugo開発サーバー起動
    deps:
      - build-css
    cmds:
      - |
        if [ "{{.OS_NAME}}" = "Darwin" ]; then
          say "Start the application."
        fi
      - hugo server --buildDrafts --buildFuture

  format:
    desc: 整形 - コードフォーマット実行
    cmds:
      - npm run format

  test:
    desc: 試験 - Playwrightテスト実行
    cmds:
      - npx playwright test --update-snapshots --headed

  ngrok:
    desc: 転送 - ngrokでローカルサーバーを公開
    cmds:
      - |
        if [ "{{.OS_NAME}}" = "Darwin" ]; then
          say "Start transfer using ngrok."
        fi
      - ngrok http 1313

  deploy:
    desc: 配備 - Netlifyへデプロイ
    cmds:
      - netlify init
      - netlify deploy {{.CLI_ARGS}}
      - |
        if [ "{{.OS_NAME}}" = "Darwin" ]; then
          say "The deployment process is complete."
        fi

  update-dependencies:
    desc: 追随 - 依存パッケージを更新
    cmds:
      - ncu --upgrade
      - rm -rfv node_modules
      - npm install
      - npx playwright install --with-deps

  update-theme:
    desc: 追随 - Congoテーマを更新
    cmds:
      - git submodule update --remote --merge themes/congo
      - npm install --prefix themes/congo

  clean:
    desc: 掃除 - テスト結果を削除
    cmds:
      - rm -rf test-results
      - rm -rf tests/*.ts-snapshots
      - |
        if [ "{{.OS_NAME}}" = "Darwin" ]; then
          say "The cleanup process is complete."
        fi
