name: Update CHANGELOG

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --output CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: :paperclip: update CHANGELOG"
          branch: chore/update-changelog
          title: "chore: :paperclip: update CHANGELOG"
          body: "CHANGELOG update by git-cliff"
          labels: "automated"

      - name: Auto-merge PR
        if: steps.create-pr.outputs.pull-request-number
        run: gh pr merge --auto --squash ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
